lang1: "Current language",
                    lang2: "English",
                    lang3: "This script increases inventory size and improves sorting of items.",
                    lang4: "Contact",
                    lang5: "<b>TW Inventory Reloaded</b>",
                    lang6: "Update",
                    lang7: "New update for userscript ",
                    lang8: "Ads <3",
                    lang9: " is available.<br><br> If you want to support development of this script, please click on Ads. It's <b> free </b> and it takes you 5 seconds<br><br><b>Version: ",
                    lang10: "TW Inventory Reloaded",
                    lang11: "No Ads!",
                    lang12: "Send me email",
                    lang13: "Adventures",
                    lang14: "Work (LP)",
                    lang15: "Duels",
                    lang16: "Energy",
                    lang17: "Motivation",
                    lang18: "Skill points",
                    lang19: "Fort Battles",
                    lang20: "Speed",
                    lang21: "Health points",
                    lang22: "Premium/special",
                    lang23: "Events",
                    lang24: "Treasures",
                    lang25: "Craft items",
                    lang26: "Field cook",
                    lang27: "Tonic peddler",
                    lang28: "Blacksmith",
                    lang29: "Master Saddler",
                    lang30: "No item found :-(",
                    lang31: "Working on it...",
                    lang32: "Done...",
                    lang33: "How many?",
                    lang34: "All usable",
                    lang35: "Recipes",
                    lang36: "Quest items",
                    lang37: "Equipment",
                    lang38: "All semi-finished",
                    lang39: "Collector cards",
                    lang40: "Construction",
                    lang41: "Vigor",
                    lang42: "Toughness",
                    lang43: "Stamina",
                    lang44: "Health Points",
                    lang45: "Horseback Riding",
                    lang46: "Reflex",
                    lang47: "Dodging",
                    lang48: "Hiding",
                    lang49: "Swimming",
                    lang50: "Aiming",
                    lang51: "Shooting",
                    lang52: "Setting Traps",
                    lang53: "Fine Motor Skills",
                    lang54: "Repairing",
                    lang55: "Leadership",
                    lang56: "Tactics",
                    lang57: "Trading",
                    lang58: "Animal Instinct",
                    lang59: "Appearance",
                    lang60: "Save",
                    lang61: "Settings saved",
                    lang60: "Ghost Town",
                    lang61: "Indian Reservation",
                    lang62: "Monday",
                    lang63: "Tuesday",
                    lang64: "Wednesday",
                    lang65: "Thursday",
                    lang66: "Friday",
                    lang67: "Saturday",
                    lang68: "Sunday",
                    lang69: "Saloon",
                    lang70: "TWIR",
                    lang71: "Daily tasks",
                    lang72: "Show products for Daily tasks",
                    lang73: "Products and crafting needed:",
                    lang74: "DT - Products",
                    lang75: "Klikni na miesto, kde chceš mať ľavý horný roh okna.",
                    lang76: "Pozice okna byla resetována.",
                    lang77: "Show only: Duplicates",
                    lang78: "<i>To see by selection, click on the category on the left and then here.</i>",
                    lang79: "Upgradeable",
                    lang80: "Without sets",
                    lang81: "Sellable",
                    lang82: "Auctionable",
                    lang83: "Show only: Usable",
                    lang84: "Show only: Craft",
                    lang85: "Show only: Sets",
                    lang86: "All sets",
                    lang87: "<u>All/ Select</u>",
                    lang88: "$ at merchant",
                    lang89: "<b>W.I.P.</b><br> Work in progress!",
                    lang90: "Center location on minimap",
                    lang91: "Show work location on map",
                    lang92: "<b>The-West Calc</b> <br>Import data to TW-Calc.",
                    lang93: "<b>Collections</b> <br>Show missing items needed for collection.",
                    lang94: "<b>Daily tasks</b> <br>Show products and crafting for Daily tasks.",
                    lang95: "<b>Pozícia okna</b> <i>Beta</i> <br>Kliknutím prejdeš do voľby novej defultnej pozície, v ktorej sa ti budú otvárať okná. (Užitočné pri väčších monitoroch).",
                    lang96: "<b>Resetovať pozíciu okna</b><br>Pre zobrazenie zmien stlač F5.",
                    lang97: "<b>Inventory style</b><br>WPI",
                    lang98: "<b>Light</b><br>Turn on/ off light :-)",
                    lang99: "Missing : ",
                    lang100: "Items for collection",
                    lang101: "%1 missing items",
                    lang102: "You have a bid for this item",
                    lang103: "Pick up this item on the market in v %1",
                    lang104: "All",
                    lang105: "By name ..",
                    lang106: "Missing items:",
                    lang107: "",
                    lang108: "Available at merchant",
                    lang109: "Auctioned",
                    lang110: "Show only items offered by merchant",
                    lang111: "Show only items that are ready to be picked up from market",
                    lang112: "Search on market",
                    lang113: "Craft",
                    lang114: "Usable",
                    lang115: "Sets",
                    lang116: "Duplicates",
                    lang117: "Select ..",
                    lang118: "Sorted by:",
                    lang119: "Recent changes to items",
                    lang120: "Dueling weapons",
                    lang121: "Guns",
                    lang122: "Headgears",
                    lang123: "Neckbands",
                    lang124: "Clothings",
                    lang125: "Belts",
                    lang126: "Trousers",
                    lang127: "Shoes",
                    lang128: "Riding animals",
                    lang129: "Products",
                    lang130: "Upgradeable",
                    lang131: "Skill",
                    lang132: "Show by: Skills",
                    lang133: "Basic > ",
                    lang134: " by: Skill",
                    lang135: "Strength",
                    lang136: "Mobility",
                    lang137: "Dexterity",
                    lang138: "Charisma",
                    lang139: "<b>Show add-ons</b>",
                    lang140: "Thank you!",
                    lang141: "If you like our script, please consider donating even a small amount to support and ensure future development of this script. We will be very grateful to you."
                }